// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using sky_egg.Models;

namespace sky_egg.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210925125851_corectDMLmigration")]
    partial class corectDMLmigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("sky_egg.Models.Feature", b =>
                {
                    b.Property<int>("FeatureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ProductFature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SkyEggProductId")
                        .HasColumnType("int");

                    b.HasKey("FeatureId");

                    b.HasIndex("SkyEggProductId");

                    b.ToTable("Features");

                    b.HasData(
                        new
                        {
                            FeatureId = 1,
                            ProductFature = "Timer & Volume Control",
                            SkyEggProductId = 1
                        },
                        new
                        {
                            FeatureId = 2,
                            ProductFature = "Much Powerful Performance - CADR 189m³/h",
                            SkyEggProductId = 2
                        },
                        new
                        {
                            FeatureId = 3,
                            ProductFature = "Effective Air Filtration - Refresh the Air in a Small or Mid-Size Room(250 Sq Ft (23 m²) )in 20 Min",
                            SkyEggProductId = 2
                        },
                        new
                        {
                            FeatureId = 4,
                            ProductFature = "EFFECTIVELY COMBAT DRYNESS;HOUGHTFUL TIMER FUNCTION",
                            SkyEggProductId = 3
                        });
                });

            modelBuilder.Entity("sky_egg.Models.Photo", b =>
                {
                    b.Property<int>("PhotoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("PhotoPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SkyEggProductId")
                        .HasColumnType("int");

                    b.HasKey("PhotoId");

                    b.HasIndex("SkyEggProductId");

                    b.ToTable("Photos");

                    b.HasData(
                        new
                        {
                            PhotoId = 1,
                            PhotoPath = "d8789136-410e-4115-95b9-4fbabc0a35fdD1 Sound Machine3.jpg",
                            SkyEggProductId = 1
                        },
                        new
                        {
                            PhotoId = 2,
                            PhotoPath = "d7ac2bd4-8645-4291-be0b-ec91afaab4c1D1 Sound Machine2.jpg",
                            SkyEggProductId = 1
                        },
                        new
                        {
                            PhotoId = 3,
                            PhotoPath = "d3fd7c36-7186-4a40-b045-b55eb71b076bD1 Sound Machine.jpg",
                            SkyEggProductId = 1
                        },
                        new
                        {
                            PhotoId = 4,
                            PhotoPath = "dc36cfbe-9fbf-455a-a4e5-7187809bdc00hepa6.png",
                            SkyEggProductId = 2
                        },
                        new
                        {
                            PhotoId = 5,
                            PhotoPath = "dfe9c871-a6fd-41d8-88cd-9b2c61aa0d50hepa5.jpg",
                            SkyEggProductId = 2
                        },
                        new
                        {
                            PhotoId = 6,
                            PhotoPath = "754fe19f-d3a4-4686-8665-c6f8c64b288ehepa4.jpg",
                            SkyEggProductId = 2
                        },
                        new
                        {
                            PhotoId = 7,
                            PhotoPath = "02826809-730c-4080-a3d3-53e9dcebbb12hepa3.png",
                            SkyEggProductId = 2
                        },
                        new
                        {
                            PhotoId = 8,
                            PhotoPath = "c13cdd4d-b4eb-4178-853c-3f6483d7208eDreamegg 2L.jpg",
                            SkyEggProductId = 3
                        });
                });

            modelBuilder.Entity("sky_egg.Models.SkyEggProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Categrie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Colors")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Prise")
                        .HasColumnType("real");

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SkyEggProducts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Categrie = "Sound_Machines",
                            Colors = "Grey",
                            Prise = 30.99f,
                            ProductName = "Dreamegg D3 Sound Machine"
                        },
                        new
                        {
                            Id = 2,
                            Categrie = "Air_Purifiers",
                            Prise = 119.99f,
                            ProductName = "HEPA Air Purifier 4-in-1 for Home"
                        },
                        new
                        {
                            Id = 3,
                            Categrie = "Humidifiers",
                            Prise = 39.99f,
                            ProductName = "Dreamegg 2L Cool Mist Humidifier - Grey"
                        });
                });

            modelBuilder.Entity("sky_egg.Models.Feature", b =>
                {
                    b.HasOne("sky_egg.Models.SkyEggProduct", "SkyEggProduct")
                        .WithMany("Features")
                        .HasForeignKey("SkyEggProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SkyEggProduct");
                });

            modelBuilder.Entity("sky_egg.Models.Photo", b =>
                {
                    b.HasOne("sky_egg.Models.SkyEggProduct", "SkyEggProduct")
                        .WithMany("Photos")
                        .HasForeignKey("SkyEggProductId");

                    b.Navigation("SkyEggProduct");
                });

            modelBuilder.Entity("sky_egg.Models.SkyEggProduct", b =>
                {
                    b.Navigation("Features");

                    b.Navigation("Photos");
                });
#pragma warning restore 612, 618
        }
    }
}
