// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using sky_egg.Models;

namespace sky_egg.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210915132602_corectData")]
    partial class corectData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("sky_egg.Models.SkyEggProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Categrie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Colors")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Features")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Prise")
                        .HasColumnType("real");

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SkyEggProducts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Categrie = "Sound_Machines",
                            Colors = "Grey",
                            Features = ";Timer & Volume Control",
                            PhotoPath = "392bbac0-796d-4c73-b0a4-5e1eb34d6b04Sound_Machines .jpg",
                            Prise = 30.99f,
                            ProductName = "Dreamegg D11 Sound Machine"
                        },
                        new
                        {
                            Id = 2,
                            Categrie = "Humidifiers",
                            Features = "Much Powerful Performance - CADR 189m³/h + True HEPA Filter;Effective Air Filtration - Refresh the Air in a Small or Mid-Size Room(250 Sq Ft (23 m²) )in 20 Min",
                            PhotoPath = "56e1d082-b379-4f50-a882-56225abdddd3HEPA.jpg",
                            Prise = 119.99f,
                            ProductName = "HEPA Air Purifier 4-in-1 for Home"
                        },
                        new
                        {
                            Id = 3,
                            Categrie = "Air_Purifiers",
                            Features = "EFFECTIVELY COMBAT DRYNESS;HOUGHTFUL TIMER FUNCTION",
                            PhotoPath = "c13cdd4d-b4eb-4178-853c-3f6483d7208eDreamegg 2L.jpg",
                            Prise = 39.99f,
                            ProductName = "Dreamegg 2L Cool Mist Humidifier - Grey"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
